title: Adyson Mombaka # your name (or website title) here
logo: "/images/image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio where I share my projects!
  <br><br>
  <a href="https://www.linkedin.com/in/adyson-mombaka/">View My LinkedIn Profile</a> 
  
theme: minimal-mistakes-jeykill
minimal_mistakes_skin: "neon"
